title: 'My Voila Homepage'
server_url: 'http://localhost:8866'
app_bar_links:
    'github': 'https://github.com/marketneutral/voila-homepage'
additional:
    my_link:
        'title': 'Another Link'
        'description': 'This is a link from the additional config.'
        'link': 'https://www.tableau.com/'
        'logo': 'https://cdns.tblsft.com/sites/all/themes/tabwat/logo.png'
